### PR TITLE
Fix 2FA sizing issue, add support for copying text from xterm.js

### LINKED ISSUE #1812: 2FA Input, Stretchs to window width.
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: Alpha 2
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Win10 / Chrome

**Describe the bug**
2FA screen stretches to the width of the window

Why You Read this??

**To Reproduce**
Login with a 2FA account...

**Expected behavior**
The input box be the same size as the first login box

### LINKED ISSUE #1813: Unable to CTRL-C selected console text
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: Alpha 2
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Win10 / Chrome

**Describe the bug**
When highlighting text in the console, CTRL-C does nothing, so you have to right-click and copy, to copy the selected text. 

**To Reproduce**
1. Start Server
2. Select text from the console
3. CTRL-C
4. Try to paste the "copied" text

**Expected behavior**
... To Copy

### PR DESCRIPTION
**Pull request by matthewpi**
Fixes #1812 (The sizing issue on the 2FA page after entering a username and password)
Fixes #1813 (The inability to copy text from xterm.js on the server console page)

### CODE REVIEW

File: resources/scripts/components/server/Console.tsx [hunk 1]
```diff
@@ -81,6 +81,17 @@ export default () => {
             // @see https://github.com/xtermjs/xterm.js/issues/2265
             // @see https://github.com/xtermjs/xterm.js/issues/2230
             TerminalFit.fit(terminal);
+
+            // Add support for copying terminal text.
+            terminal.attachCustomKeyEventHandler((e: KeyboardEvent) => {
+                // Ctrl + C
+                if (e.ctrlKey && (e.key === 'c')) {
+                    document.execCommand('copy');
+                    return false;
```
Comment (schrej) [inline resources/scripts/components/server/Console.tsx]: isn't just the `return false` sufficient?

**Comment by schrej** [comment]
Also commit messages where you actually say what you did and just reference the commits in the body are much more useful. Same applies for PRs.

File: resources/scripts/components/server/Console.tsx (hunk 1 above)
Comment (matthewpi) [reply resources/scripts/components/server/Console.tsx]: From what I understand, the `return false` prevents xterm.js from processing the event, while `return true` allows all additional events to be handled.  So while the extra return might not be necessary because xterm.js does not do anything observable with `Ctrl+C`, it should probably be left there.

https://xtermjs.org/docs/api/terminal/classes/terminal/#attachcustomkeyeventhandler

Comment (schrej) [reply resources/scripts/components/server/Console.tsx]: I'd assume if you prevent xterm from processing it by returning false, it shouldn't consume the event. It therefore propagates until the browser itself consumes it and copies the text. Just listening for keyboard events doesn't disable all of them, does it?

**Comment by schrej** [comment]
Also, for the future, please separate fixes into individual pull requests. This way, in case one of them is unwanted or not ready yet, they can be merged individually.

**Comment by matthewpi** [comment]
I could separate the commits into two pull requests if you don’t want to merge both.

**Comment by DaneEveritt** [comment]
@schrej I told him he could just do a single PR for this since we're just trying to knock out bugs.

**Comment by schrej** [comment]
Ah ok. I also meant it in a general sense, no need to split them up now. It's just a little cleaner that way, and most other projects would also prefer it like that I assume.

**Comment by DaneEveritt** [comment]
> Ah ok. I also meant it in a general sense, no need to split them up now. It's just a little cleaner that way, and most other projects would also prefer it like that I assume.

Ah, yes, that is generally how I prefer them. :)
