### PR TITLE
fix: exclude any permissions not defined internally when updating or creating users

### LINKED ISSUE #4328: Subuser permissions are not validated
### Current Behavior

When creating or updating a subuser via the API, the `permissions` field will accept any value, regardless of whether it is a valid permission or not.

### Expected Behavior

These endpoints should validate the permissions field before continuing with the request.

### Steps to Reproduce

1. Put random characters or numbers, anything but a valid permission in the `permissions` field of the request body
2. Request `POST /api/client/servers/<identifier>/users` or `POST /api/client/servers/<identifier>/users/<uuid>` if you have a subuser to test on

### Panel Version

1.10.1

### Wings Version

1.7.0

### Games and/or Eggs Affected

N/A

### Docker Image

N/A

### Error Logs

```bash
N/A
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

### PR DESCRIPTION
**Pull request by DaneEveritt**
Drops any permissions we don't track internally on the `Permission` model, and adds test coverage for the update logic.

closes #4328

### CODE REVIEW

File: app/Policies/ServerPolicy.php [hunk 1]
```diff
@@ -2,45 +2,22 @@
...
     {
-        $key = sprintf('ServerPolicy.%s.%s', $user->uuid, $server->uuid);
-
-        $permissions = $this->cache->remember($key, Carbon::now()->addSeconds(5), function () use ($user, $server) {
-            /** @var \Pterodactyl\Models\Subuser|null $subuser */
-            $subuser = $server->subusers()->where('user_id', $user->id)->first();
-
-            return $subuser ? $subuser->permissions : [];
-        });
+        $subuser = $server->subusers->where('user_id', $user->id)->first();
```
Comment (DaneEveritt) [inline app/Policies/ServerPolicy.php:15]: This caching was unnecessary so long as everything in the request continues passing the same server model around — the subusers relationship will stay loaded.

**Review by matthewpi — APPROVED** [review]
