### PR TITLE
Fix schedule layout

### LINKED ISSUE #2346: A command that is too long will break the design
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.0 RC5
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Windows 10 20H2, Google Chrome

**Describe the bug**
```
PHP 7.4.3 (cli) (built: May 26 2020 12:24:22) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
```

**To Reproduce**
1. Go to the server.
2. Click on schedules.
3. Setup the schedule.
4. Set the long command.

Capture

**Expected behavior**
A command that is too long will no break the design.

### PR DESCRIPTION
**Pull request by notAreYouScared**
Limiting Schedule name 75>255
Moved Payload to bottom of new task window
Closes #2346

### CODE REVIEW

**Review by DaneEveritt — APPROVED** [review]

File: app/Models/Schedule.php [hunk 1]
```diff
@@ -103,7 +103,7 @@ class Schedule extends Model
      */
     public static $validationRules = [
         'server_id' => 'required|exists:servers,id',
-        'name' => 'nullable|string|max:255',
+        'name' => 'nullable|string|max:75',
```
Comment (DaneEveritt) [inline app/Models/Schedule.php:106]: This change will break all of the schedules that already have a longer name until someone manually edits it to have a shorter name.

**Review by DaneEveritt — CHANGES_REQUESTED** [review]

File: app/Models/Schedule.php (hunk 1 above)
Comment (Sir3lit) [reply app/Models/Schedule.php]: Changed back to 255

**Review by DaneEveritt — APPROVED** [review]
