### PR TITLE
fix: backup restore delete all files

### LINKED ISSUE #3178: Delete all files before restore does not work.
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon:  1.3.1
* Server's OS: Debian 10
* Your Computer's OS & Browser: Windows 10 Firefox

**Describe the bug**
When selecting to delete all files before restoring from backup, that checkbox isn't actually passed. It's just ignored.

**To Reproduce**
1. Restore from backup.
2. Select delete all files first
3. Watch it not delete the files

**Expected behavior**
It should delete the files and not keep them.

### PR DESCRIPTION
**Pull request by matthewpi**

### CODE REVIEW

File: resources/scripts/components/server/backups/BackupContextMenu.tsx [hunk 1]
```diff
@@ -108,6 +109,8 @@ export default ({ backup }: Props) => {
                             css={tw`text-red-500! w-5! h-5! mr-2`}
                             id={'restore_truncate'}
                             value={'true'}
+                            checked={truncate}
+                            onChange={() => setTruncate(!truncate)}
```
Comment (DaneEveritt) [inline resources/scripts/components/server/backups/BackupContextMenu.tsx]: `setTruncate(s => !s)`

File: resources/scripts/components/server/backups/BackupContextMenu.tsx [hunk 2]
```diff
@@ -87,7 +88,7 @@ export default ({ backup }: Props) => {
                 visible={modal === 'restore'}
                 title={'Restore this backup?'}
                 buttonText={'Restore backup'}
-                onConfirmed={() => doRestorationAction()}
+                onConfirmed={() => doRestorationAction(truncate)}
```
Comment (DaneEveritt) [inline resources/scripts/components/server/backups/BackupContextMenu.tsx]: Don't need to pass truncate here, just pull it from the set state.

**Review by DaneEveritt — CHANGES_REQUESTED** [review]
