### PR TITLE
Switch to s3 multipart uploads for backups

### LINKED ISSUE #2599: S3 backups cannot upload files larger than 5GB
* Panel or Daemon: Wings
* Version of Panel/Daemon: 1.0.1
* Server's OS: Debian 10.5
* Your Computer's OS & Browser: Windows 10 Firefox

**Describe the bug**
When creating a backup larger than 5GB upload fails to S3. This is due to limitations in s3 put requests via http.
**To Reproduce**
1. Configure s3 storage option on panel
2. Create backup of service that is over 5GB
3. Watch it crash and burn.

**Expected behavior**
Wings needs to use either MultiPart uploads via HTTP or use AWS SDK for Go.

MultiPart Upload Information:
https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingRESTAPImpUpload.html

Go API:
https://docs.aws.amazon.com/sdk-for-go/api/

### PR DESCRIPTION
**Pull request by matthewpi**
Resolves #2599 

Requires https://github.com/pterodactyl/wings/pull/67

### CODE REVIEW

File: app/Http/Controllers/Api/Remote/Backups/BackupRemoteUploadController.php [hunk 1]
```diff
@@ -0,0 +1,128 @@
...
+     * @param \Pterodactyl\Extensions\Backups\BackupManager $backupManager
+     */
+    public function __construct(BackupRepository $repository, BackupManager $backupManager)
+    {
+        $this->repository = $repository;
+        $this->backupManager = $backupManager;
+    }
+
+    /**
+     * ?
```
Comment (DaneEveritt) [inline app/Http/Controllers/Api/Remote/Backups/BackupRemoteUploadController.php]: ?

File: app/Http/Controllers/Api/Remote/Backups/BackupRemoteUploadController.php [hunk 2]
```diff
@@ -0,0 +1,128 @@
...
+     *
+     * @return \Illuminate\Http\JsonResponse
+     *
+     * @throws \Pterodactyl\Exceptions\Repository\RecordNotFoundException
+     * @throws \Exception
+     */
+    public function __invoke(Request $request, string $backup)
+    {
+        $size = $request->query('size', null);
+        if ($size === null) {
```
Comment (DaneEveritt) [inline app/Http/Controllers/Api/Remote/Backups/BackupRemoteUploadController.php]:
```suggestion
        if (if_null($size)) {
```

File: app/Http/Controllers/Api/Remote/Backups/BackupRemoteUploadController.php [hunk 3]
```diff
@@ -0,0 +1,128 @@
...
+            return new JsonResponse([], JsonResponse::HTTP_BAD_REQUEST);
```
Comment (DaneEveritt) [inline app/Http/Controllers/Api/Remote/Backups/BackupRemoteUploadController.php]: This should probably throw a `BadRequestHttpException` or `DisplayException` or something, try to avoid error responses with no details.

File: app/Http/Controllers/Api/Remote/Backups/BackupRemoteUploadController.php [hunk 4]
```diff
@@ -0,0 +1,128 @@
...
+        }
+
+        /** @var \Pterodactyl\Models\Backup $model */
+        $model = $this->repository->findFirstWhere([[ 'uuid', '=', $backup ]]);
```
Comment (DaneEveritt) [inline app/Http/Controllers/Api/Remote/Backups/BackupRemoteUploadController.php]: I've given up on the repositories for most query things BTW, you can just do `Model::query()->...` if you prefer.

File: app/Http/Controllers/Api/Remote/Backups/BackupRemoteUploadController.php [hunk 5]
```diff
@@ -0,0 +1,128 @@
...
+                    'UploadId' => $uploadId,
+                    'PartNumber' => $i + 1,
+                ]),
+                CarbonImmutable::now()->addMinutes(30)
+            );
+
+           array_push($parts, $part->getUri()->__toString());
+        }
+
+        return new JsonResponse([
```
Comment (DaneEveritt) [inline app/Http/Controllers/Api/Remote/Backups/BackupRemoteUploadController.php:137]: All endpoints in the Panel return `lower_snake_case` for keys.

File: app/Http/Controllers/Api/Remote/Backups/BackupRemoteUploadController.php [hunk 6]
```diff
@@ -0,0 +1,128 @@
...
+            'CompleteMultipartUpload' => $completeMultipartUpload->getUri()->__toString(),
+            'AbortMultipartUpload' => $abortMultipartUpload->getUri()->__toString(),
+            'Parts' => $parts,
+            'PartSize' => self::PART_SIZE,
+        ], JsonResponse::HTTP_OK);
```
Comment (DaneEveritt) [inline app/Http/Controllers/Api/Remote/Backups/BackupRemoteUploadController.php]: `HTTP_OK` is redundant and can be left off.

File: app/Http/Controllers/Api/Remote/Backups/BackupRemoteUploadController.php [hunk 7]
```diff
@@ -0,0 +1,128 @@
...
+                'Key' => $path,
+                'ContentType' => 'application/x-gzip',
+                'UploadId' => $uploadId,
+            ]),
+            CarbonImmutable::now()->addMinutes(30)
+        );
+
+        $abortMultipartUpload = $client->createPresignedRequest(
+            $client->getCommand('AbortMultipartUpload', [
+                'Bucket' => $adapter->getBucket(),
```
Comment (DaneEveritt) [inline app/Http/Controllers/Api/Remote/Backups/BackupRemoteUploadController.php]: Can probably make an array variable with the Bucket, Key, and ContentType already set and just do an array_merge($var, []) on it for all of these, would make the code a little easier to follow and less repetitive.

**Review by DaneEveritt — CHANGES_REQUESTED** [review]
